name: Build Valorant Autorecord

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build --configuration Release
      - name: Publish
        run: |
          dotnet publish -c Release -o ./publish
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ValorantAutorecord
          path: ./publish
