name: Build on Push
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 9.1.1
      - run: pnpm install --frozen-lockfile

      - run: npm run package --if-present

      - uses: actions/upload-artifact@v4
        with:
          name: Windows Executable
          path: build/*.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: build/*.exe
